[tool.poetry]
name = "ethlib"
version = "0.1.0"
description = ""
authors = ["Edward Amor <edward.amor3@gmail.com>"]
license = "LGPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
